"""empty message

Revision ID: d5581df5ac12
Revises: 90112bf1db3a
Create Date: 2019-05-24 20:18:15.248886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5581df5ac12'
down_revision = '90112bf1db3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Reward_Rank',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('share_id', sa.BIGINT(), nullable=False),
    sa.Column('activity_id', sa.BIGINT(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('nickname', sa.String(length=150, collation='utf8mb4_bin'), nullable=True),
    sa.Column('head_url', sa.String(length=120, collation='utf8mb4_bin'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Withdraw_Bank',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('merchant_id', sa.INTEGER(), nullable=True),
    sa.Column('bank_name', sa.String(length=120, collation='utf8mb4_bin'), nullable=True),
    sa.Column('card_no', sa.String(length=64, collation='utf8mb4_bin'), nullable=True),
    sa.Column('id_no', sa.String(length=64, collation='utf8mb4_bin'), nullable=True),
    sa.Column('real_name', sa.String(length=120, collation='utf8mb4_bin'), nullable=True),
    sa.Column('bank_branch', sa.String(length=120, collation='utf8mb4_bin'), nullable=True),
    sa.Column('create_time', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('merchant_id', sa.INTEGER(), nullable=True),
    sa.Column('media_resource', sa.JSON(), nullable=True),
    sa.Column('desc', sa.String(length=500, collation='utf8mb4_bin'), nullable=True),
    sa.Column('bottom_text', sa.String(length=50), nullable=True),
    sa.Column('target_url', sa.String(length=255), nullable=True),
    sa.Column('create_time', sa.INTEGER(), nullable=True),
    sa.Column('update_time', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('With_Draw_Bank')
    op.add_column('Activity', sa.Column('enroll_count', sa.INTEGER(), nullable=True))
    op.add_column('CustomerService', sa.Column('merchant_id', sa.BIGINT(), nullable=True))
    op.add_column('RetailReward', sa.Column('activity_id', sa.BIGINT(), nullable=False))
    op.add_column('RetailReward', sa.Column('merchant_id', sa.BIGINT(), nullable=False))
    op.drop_column('RetailReward', 'activty_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RetailReward', sa.Column('activty_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
    op.drop_column('RetailReward', 'merchant_id')
    op.drop_column('RetailReward', 'activity_id')
    op.drop_column('CustomerService', 'merchant_id')
    op.drop_column('Activity', 'enroll_count')
    op.create_table('With_Draw_Bank',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('merchant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('bank_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=120), nullable=True),
    sa.Column('card_no', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=64), nullable=True),
    sa.Column('id_no', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=64), nullable=True),
    sa.Column('real_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=120), nullable=True),
    sa.Column('bank_branch', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=120), nullable=True),
    sa.Column('create_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('merchant_detail')
    op.drop_table('Withdraw_Bank')
    op.drop_table('Reward_Rank')
    # ### end Alembic commands ###
